insert into shops (id, "name", "desc", "picUrl")
values(101, 'Maryanne Mixes','Hi! Welcome to Maryanne Mixes, we are located in Seattle and we love a refreshing drink, dont you? All of our drinks are made fresh and on-location. They are all sold in 12 oz glass bottles! If you love your drink and you love the environment you can send the bottles back and receive two free drinks on your next order!', 'https://images.unsplash.com/photo-1592154016856-52ac296fc27a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjZ8fGp1aWNlfGVufDB8MnwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60'),
(102, 'The Goats Plan','Have you ever wondered where your cheese comes from? Here at the Goats Plan we tell you! Fanny our goat, and Mary and Nanny, our Cows work extra hard to provide us with the most heavenly cheeses. They live very lavish lifestyles free from stress, and they create all of our local cheeses! We tell you exactly where your cheese is from, so find out who your favorite is today.', 'https://images.unsplash.com/photo-1603480372719-cee90a49b202?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'),
(103, 'Great Balls of Chocolate','We are a sister pair from North Carolina with over 8 years of chocolatier experience! All of our balls are sold by the dozen, and the bars are sold individually. Chocolate done well is sinfully delicious we we hope you love our great big chocolatey balls.', 'https://images.unsplash.com/photo-1583312228158-4001fca6e316?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'),
(104, 'Ice-Cold Ice-Creams','Cold Creamy (Homemade) ice cream is incomparable to store bought. All of our ice creams are sold by the pint and shipped overnight on dry ice to ensure they arrive in perfect, frozen condition. Treat yourself and your loved ones to our delicious flavors.', 'https://images.unsplash.com/photo-1526653054275-5a4f37ea1c64?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'),
(105, 'Bravisimo','Coffee is our passion, lifestyle, and dream come true! Our small home-owned coffee shop hosts local brews, grounds, and whole beans. We promise quality, care, and consistency. All of our grounds are sold per 12 oz. bag and hold around 10 cups each!', 'https://images.unsplash.com/photo-1509650911013-64ffddfcfe58?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'),
(106, 'Cookie Delight','Coffee is our passion, lifestyle, and dream come true! Our small home-owned coffee shop hosts local brews, grounds, and whole beans. We promise quality, care, and consistency. All of our grounds are sold per 12 oz. bag and hold around 10 cups each!', 'https://images.unsplash.com/photo-1547562475-d5c9cead07f0?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'),
(107, 'Sissys New York','From the late-night streets of New York to you at home we hope you try our super fun desserts. Color, Flavor, and Fun is our thing. All items sold individually.', 'https://images.unsplash.com/photo-1511559714511-3181c09c1cb0?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8MXwyMDY3OTE2fHxlbnwwfHx8&auto=format&fit=crop&w=400&q=60'),
(108, 'Grans Classics','Melinda and Jason opened up their home-bakery store in 2013 to honor their Grandmother, Ada. Ada left them with a passion for baking, and some incredible recipes. They have since chased their dreams of baking love into every bite.', 'https://images.unsplash.com/photo-1447949122973-9711a09951d5?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8dGVhJTIwY3VwfGVufDB8MnwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60'),
(109, 'Granola Sunrise','Locally Sourced, Environmentally Minded, and 100% California. Granola Sunrise strives to bring you delicious treats with ingredients that are kind to you and your body.', 'https://images.unsplash.com/photo-1527614853535-bc948bbb3e5e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'),
(110, 'Patisserie De La Claude','French baker, Claude Bermoise, has opened his own home-based shop to bring you the sweetest french gourmet pastries. Cest délicieux. (It is delicious!)', 'https://images.unsplash.com/photo-1596957901846-a0722f546502?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=782&q=80'),
(111, 'Big Bad Brownies','Chocolate Lovers and welcome here at Big Bad Brownies! We dont hold back, and our brownies are the best on the block! All items are sold individually.', 'https://images.unsplash.com/photo-1588258382591-5725de4bb861?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80'),
(112, 'San Fran Sourdough','Bread is our Art and we love Art! My husband, Joe and I appreciate the fine details of bread. We create real, crusty, chewy, delicious bakery-style loaves that taste incredible with dips, soups, sauces, and comforting dinners. We wanted to share our Art with the world, and hope you enjoy it as well.', 'https://images.unsplash.com/photo-1556471013-0001958d2f12?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=823&q=80')